import React, { useState, useRef } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Sparkles, ShieldCheck, Key, ArrowRight, ArrowLeft } from 'lucide-react';
import { useApp } from '../../context/AppContext';

export const TwoFactorPage: React.FC = () => {
  const { login, showToast } = useApp();
  const navigate = useNavigate();
  const [digits, setDigits] = useState<string[]>(['', '', '', '', '', '']);
  const [useBackup, setUseBackup] = useState(false);
  const [backupCode, setBackupCode] = useState('');
  const inputRefs = useRef<(HTMLInputElement | null)[]>([]);

  const handleDigitChange = (index: number, val: string) => {
    if (val.length > 1) {
      val = val.slice(-1);
    }
    const newDigits = [...digits];
    newDigits[index] = val;
    setDigits(newDigits);

    if (val && index < 5) {
      inputRefs.current[index + 1]?.focus();
    }
  };

  const handleKeyDown = (index: number, e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Backspace' && !digits[index] && index > 0) {
      inputRefs.current[index - 1]?.focus();
    }
  };

  const handleVerify = (e: React.FormEvent) => {
    e.preventDefault();
    const token = digits.join('');
    if (!useBackup && token.length < 6) {
      showToast({ type: 'warning', title: 'Incomplete OTP', message: 'Please enter all 6 digits.' });
      return;
    }

    login('alex.vance@omnicommerce.io');
    showToast({
      type: 'success',
      title: '2FA Verification Successful',
      message: 'Biometric cryptographic identity verified.',
    });
    navigate('/dashboard');
  };

  return (
    <div className="min-h-screen bg-[#F8F9FC] flex flex-col justify-center items-center px-4">
      <div className="flex items-center gap-3 mb-8">
        <div className="w-10 h-10 rounded-xl bg-[#1A1F36] text-white flex items-center justify-center font-bold text-xl shadow-md">
          <Sparkles className="w-6 h-6 text-[#5B6FF5]" />
        </div>
        <span className="text-xl font-bold tracking-tight text-[#111827]">OmniCommerce</span>
      </div>

      <div className="bg-white max-w-md w-full rounded-2xl border border-[#E5E8F0] shadow-card p-8 text-center">
        <div className="w-12 h-12 rounded-xl bg-[#5B6FF5]/10 text-[#5B6FF5] flex items-center justify-center mx-auto mb-4">
          <ShieldCheck className="w-6 h-6" />
        </div>

        <h2 className="text-2xl font-bold text-[#111827] tracking-tight">Two-Factor Authentication</h2>
        <p className="text-xs text-[#6B7280] mt-1.5 leading-relaxed">
          {useBackup
            ? 'Enter one of your 8-character alphanumeric emergency recovery codes.'
            : 'Enter the 6-digit code generated by your Authenticator app (Google Authenticator, 1Password, or YubiKey).'}
        </p>

        <form onSubmit={handleVerify} className="mt-6 space-y-6">
          {!useBackup ? (
            <div className="flex justify-center gap-2">
              {digits.map((digit, idx) => (
                <input
                  key={idx}
                  ref={(el) => {
                    inputRefs.current[idx] = el;
                  }}
                  type="text"
                  inputMode="numeric"
                  pattern="[0-9]*"
                  maxLength={1}
                  value={digit}
                  onChange={(e) => handleDigitChange(idx, e.target.value)}
                  onKeyDown={(e) => handleKeyDown(idx, e)}
                  autoFocus={idx === 0}
                  className="w-11 h-12 text-center text-lg font-bold font-mono bg-[#F8F9FC] border border-[#E5E8F0] rounded-lg focus:border-[#5B6FF5] focus:bg-white outline-hidden transition-all text-[#111827]"
                />
              ))}
            </div>
          ) : (
            <div>
              <input
                type="text"
                required
                value={backupCode}
                onChange={(e) => setBackupCode(e.target.value)}
                placeholder="XXXX-XXXX-XXXX"
                className="w-full px-4 py-2.5 bg-[#F8F9FC] border border-[#E5E8F0] rounded-lg text-sm text-center font-mono uppercase tracking-wider focus:border-[#5B6FF5] outline-hidden"
              />
            </div>
          )}

          <button
            type="submit"
            className="w-full py-2.5 px-4 bg-[#5B6FF5] hover:bg-[#4557E0] text-white text-sm font-semibold rounded-lg shadow-sm transition-all flex items-center justify-center gap-2"
          >
            <span>Verify & Authenticate</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </form>

        <div className="mt-6 pt-4 border-t border-[#E5E8F0] flex items-center justify-between text-xs">
          <button
            type="button"
            onClick={() => setUseBackup(!useBackup)}
            className="text-[#5B6FF5] font-semibold hover:underline flex items-center gap-1"
          >
            <Key className="w-3.5 h-3.5" />
            <span>{useBackup ? 'Use standard TOTP' : 'Use backup recovery code'}</span>
          </button>

          <Link to="/login" className="text-[#6B7280] hover:text-[#111827] flex items-center gap-1">
            <ArrowLeft className="w-3.5 h-3.5" /> Back to login
          </Link>
        </div>
      </div>
    </div>
  );
};
